### ISSUE TITLE
No target 

### ISSUE THREAD

**Issue by dok441** [Alf21/ttt2-role_hit#11]
![хитман](https://user-images.githubusercontent.com/7480655/84572538-5ecd2a80-ada3-11ea-85d9-c7ef6e924832.png)
As you can see in the screenshot, there is no goal, this happens quite rarely, the reason is unknown to me, I use the latest version.

**Comment by TimGoll** [comment]
Should be fixed by https://github.com/TTT-2/ttt2-role_hit/commit/3b18846660e27eb8b126c39af0c0117d0f6d00c4
