### ISSUE TITLE
Interfering with sandbox gamemode when subscribed onto client and p2p or local server created

### ISSUE THREAD

**Issue by cafelargo** [Alf21/ttt2-role_hit#12]
This role removes previously applied playermodels and does not give players items upon spawn if this addon is subscribed to and sandbox is loaded up. If you include `if engine.ActiveGamemode() ~= "terrortown" then return end` into all of your lua\autorun files this will be fixed

**Comment by mexikoedi** [comment]
I think this should be fixed by now because of the new folder/file structure.
