### ISSUE TITLE
Target Exceptions

### ISSUE THREAD

**Issue by mexikoedi** [Alf21/ttt2-role_hit#17]
Maybe add an exception for some roles that should not be killed by the hitman.
For example neutral roles like the medic and maybe some other roles with TEAM_NONE.

**Comment by TimGoll** [comment]
Should be fixed by: https://github.com/TTT-2/ttt2-role_hit/commit/3b18846660e27eb8b126c39af0c0117d0f6d00c4

Use the following code in your role to prevent the role from being selected:

```lua
hook.Add("TTT2CanBeHitmanTarget", "TTT2SpyNoHitmanTarget", function(hitman, ply)
	if ply:GetSubRole() == ROLE_SPY then
		return false
	end
end)
```
