### ISSUE TITLE
Console error

### ISSUE THREAD

**Issue by Shaknunic** [Alf21/ttt2-role_hit#2]
This happened from nowhere, probably when the target is killed or commit suicide.

[ERROR] ttt2/lua/autorun/client/ttttargetclienthit.lua:187: attempt to index field 'HITMAN' (a nil value)
  1. fn - addons/[ttt]_ttt2/lua/autorun/client/ttttargetclienthit.lua:187
   2. unknown - addons/ulx+ulib-beta+ttt2/lua/ulib/shared/hook.lua:109

**Comment by Alf21** [comment]
You are using an old version. Check this erroring line on GitHub, it‘s an empty one. So it can‘t be caused on the newest version.
